schema = 3

[mod]
  [mod."9fans.net/go"]
    version = "v0.0.5"
    hash = "sha256-xsv3DkQS067Kaxprd4eRFZVsNVBJ/Px19QbHJjOmq10="
  [mod."github.com/alecthomas/gometalinter"]
    version = "v3.0.0+incompatible"
    hash = "sha256-UaxB4Yye3bCS0Wt+/ftdc0D0R0NnEdPfChkYup0/fMg="
  [mod."github.com/alecthomas/kong"]
    version = "v0.9.0"
    hash = "sha256-5tojaBT73EB/IY8MewNjzJnNTQ+5jSw2Nxe3IjLSwXA="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20231202071711-9a357b53e9c9"
    hash = "sha256-nOY+C6mkdVA38WHiwUgmsMJO7YzQJZ9yD3cZcQM7iio="
  [mod."github.com/apex/log"]
    version = "v1.9.0"
    hash = "sha256-IkK3i208GhxMNT6GUl5O5gVSCvXOT/Fo5IyjZZmdeMU="
  [mod."github.com/beevik/ntp"]
    version = "v1.4.1"
    hash = "sha256-rwL89tsYU+1mvooRBYfdwsqP/j015YN28dM7TCpkKSY="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/davidrjenni/reftools"]
    version = "v0.0.0-20240211192525-f5f96ef18854"
    hash = "sha256-7X+yqIPKGfdOVVMgfCVm8VlY9VIw6ZlTqIIh6xGaIL4="
  [mod."github.com/fatih/camelcase"]
    version = "v1.0.0"
    hash = "sha256-VPzLJ5R6kWzrCwggUOhHlQ3XKW6nCOXxn+0kWZzh+Xw="
  [mod."github.com/fatih/color"]
    version = "v1.7.0"
    hash = "sha256-4In7ef7it7d+6oGUJ3pkD0V+lsL40hVtYdy2KD2ovn0="
  [mod."github.com/fatih/gomodifytags"]
    version = "v1.16.0"
    hash = "sha256-prr34frdKUrPkotN2C31E9Ivxq+6sAF2icnq3WqyE/o="
  [mod."github.com/fatih/motion"]
    version = "v1.2.0"
    hash = "sha256-7vkMhjO4JUAf0sUcKiMjqJ5GzLb//QoHd7Cagerx4/s="
  [mod."github.com/fatih/structtag"]
    version = "v1.2.0"
    hash = "sha256-Y2pjiEmMsxfUH8LONU2/f8k1BibOHeLKJmi4uZm/SSU="
  [mod."github.com/google/shlex"]
    version = "v0.0.0-20191202100458-e7afc7fbc510"
    hash = "sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM="
  [mod."github.com/josharian/impl"]
    version = "v1.3.0"
    hash = "sha256-a9jAoZp/wVnTyaE4l2yWSf5aSxXEtqN6SoxU68XhRhk="
  [mod."github.com/jstemmer/gotags"]
    version = "v1.4.1"
    hash = "sha256-cHTgt+zW6S6NDWBE6NxSXNPdn84CLD8WmqBe+uXN8sA="
  [mod."github.com/kisielk/errcheck"]
    version = "v1.7.0"
    hash = "sha256-hl1EbAO4okfTahl+1WDsFuVgm6Ba98Ji0hxqVe7jGbk="
  [mod."github.com/klauspost/asmfmt"]
    version = "v1.3.2"
    hash = "sha256-YxIVqPGsqxvOY0Qz4Jw5FuO9IbplCICjChosnHrSCgc="
  [mod."github.com/koron/iferr"]
    version = "v0.0.0-20240122035601-9c3e2fbe4bd1"
    hash = "sha256-qGuSsdQorb407rDl2o7w7kPCLng3W7YQsqo5JpoZFW8="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.2"
    hash = "sha256-dkRbC2vKUIMndsFfO2IuFhGHPXU89ZTasXP+ykeVIhQ="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.8"
    hash = "sha256-EMWTTlMvuXlCpExYw88VJYDwULXx+Ckuqrw4I3OADmc="
  [mod."github.com/mdempsky/gocode"]
    version = "v0.0.0-20200405233807-4acdcbdea79d"
    hash = "sha256-TRghfTqJRaYKC8HqGFBEic01X90quKT5CSCUsO8RjP4="
  [mod."github.com/nicksnyder/go-i18n"]
    version = "v1.10.3"
    hash = "sha256-ISsuydETL+NjDpSKl377pBNqnQHbxsNf2n3wZsBLGD4="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.5"
    hash = "sha256-RJ9K1BTId0Mled7S66iGgxHkZ5JKEIsrrNaEfM8aImc="
  [mod."github.com/pkg/errors"]
    version = "v0.8.1"
    hash = "sha256-oe3iddfoLRwpC3ki5fifHf2ZFprtg99iNak50shiuDw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.19.0"
    hash = "sha256-YV8sxMPR+xorTUCriTfcFsaV2b7PZfPJDQmOgUYOZJo="
  [mod."github.com/prometheus/client_model"]
    version = "v0.5.0"
    hash = "sha256-/sXlngf8AoEIeLIiaLg6Y7uYPVq7tI0qnLt0mUyKid4="
  [mod."github.com/prometheus/common"]
    version = "v0.48.0"
    hash = "sha256-gXer/9So7DxDP3cBQp8sIzJXP5whT8sk31FURoij5Do="
  [mod."github.com/prometheus/procfs"]
    version = "v0.12.0"
    hash = "sha256-Y4ZZmxIpVCO67zN3pGwSk2TcI88zvmGJkgwq9DRTwFw="
  [mod."github.com/rogpeppe/godef"]
    version = "v1.1.2"
    hash = "sha256-URW3aLO14hReJR30zfOQ+xHu9zZ5MdxXBWTZOOrBR6Y="
  [mod."github.com/zmb3/gogetdoc"]
    version = "v0.0.0-20190228002656-b37376c5da6a"
    hash = "sha256-fRfHgQcO2RrBaxRXlb6C9xVvre6pXkkzBNyccvDzS74="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20210508222113-6edffad5e616"
    hash = "sha256-U4o4PZ8KRpwbUN+E0VwewWNCiK5OGeBIpAMLJEbO9Ng="
  [mod."golang.org/x/mod"]
    version = "v0.17.0"
    hash = "sha256-CLaPeF6uTFuRDv4oHwOQE6MCMvrzkUjWN3NuyywZjKU="
  [mod."golang.org/x/net"]
    version = "v0.25.0"
    hash = "sha256-IjFfXLYNj27WLF7vpkZ6mfFXBnp+7QER3OQ0RgjxN54="
  [mod."golang.org/x/sync"]
    version = "v0.7.0"
    hash = "sha256-2ETllEu2GDWoOd/yMkOkLC2hWBpKzbVZ8LhjLu0d2A8="
  [mod."golang.org/x/sys"]
    version = "v0.20.0"
    hash = "sha256-mowlaoG2k4n1c1rApWef5EMiXd3I77CsUi8jPh6pTYA="
  [mod."golang.org/x/tools"]
    version = "v0.21.0"
    hash = "sha256-TU0gAxUX410AYc/nMxxZiaqXeORih1cXbKh3sxKufVg="
  [mod."golang.org/x/tools/cmd/guru"]
    version = "v0.1.1-deprecated"
    hash = "sha256-nNUiIDcmX6HF/Fa6GHP6vrW7Uk3DmhBcF3izBDdURdA="
  [mod."google.golang.org/protobuf"]
    version = "v1.32.0"
    hash = "sha256-GJuTkMGHCzHbyK4yD5kY4oMn8wQWqgkeBK//yVDqHJk="
  [mod."gopkg.in/alecthomas/kingpin.v3-unstable"]
    version = "v3.0.0-20191105091915-95d230a53780"
    hash = "sha256-jFnBrGgnSx6Nzd3Okpn0JG9bR9cwodNIJUI4HxD94lk="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."honnef.co/go/tools"]
    version = "v0.4.7"
    hash = "sha256-aE44owPaESdPFiCyKUoUmUPchfHASwTuF/LZDlwLGVY="
