---

name: Build & test golang package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Setup just
        run: sudo snap install --edge --classic just

      - name: Build
        run: just build

      - name: Test
        run: just test

