---
name: Build & publish executable packages for common OS-es


on:
  push:
    tags:
      - '*'


jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Test
        run: just test

      - name: Build packages
        run: just build-all

      - name: Publish packages
        uses: actions/upload-artifact@v4
        with:
          path: ./klokkijker_*
          if-no-files-found: error
